/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTestSuitesRouteImport } from './routes/_authenticated/test-suites'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQaGuideRouteImport } from './routes/_authenticated/qa-guide'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedNewAnalysisRouteImport } from './routes/_authenticated/new-analysis'
import { Route as AuthenticatedLocatorSandboxRouteImport } from './routes/_authenticated/locator-sandbox'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApiTesterRouteImport } from './routes/_authenticated/api-tester'
import { Route as AuthenticatedResultsAnalysisIdRouteImport } from './routes/_authenticated/results.$analysisId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestSuitesRoute = AuthenticatedTestSuitesRouteImport.update({
  id: '/test-suites',
  path: '/test-suites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaGuideRoute = AuthenticatedQaGuideRouteImport.update({
  id: '/qa-guide',
  path: '/qa-guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewAnalysisRoute =
  AuthenticatedNewAnalysisRouteImport.update({
    id: '/new-analysis',
    path: '/new-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocatorSandboxRoute =
  AuthenticatedLocatorSandboxRouteImport.update({
    id: '/locator-sandbox',
    path: '/locator-sandbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiTesterRoute = AuthenticatedApiTesterRouteImport.update({
  id: '/api-tester',
  path: '/api-tester',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsAnalysisIdRoute =
  AuthenticatedResultsAnalysisIdRouteImport.update({
    id: '/results/$analysisId',
    path: '/results/$analysisId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-tester': typeof AuthenticatedApiTesterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/locator-sandbox': typeof AuthenticatedLocatorSandboxRoute
  '/new-analysis': typeof AuthenticatedNewAnalysisRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/qa-guide': typeof AuthenticatedQaGuideRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/test-suites': typeof AuthenticatedTestSuitesRoute
  '/results/$analysisId': typeof AuthenticatedResultsAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api-tester': typeof AuthenticatedApiTesterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/locator-sandbox': typeof AuthenticatedLocatorSandboxRoute
  '/new-analysis': typeof AuthenticatedNewAnalysisRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/qa-guide': typeof AuthenticatedQaGuideRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/test-suites': typeof AuthenticatedTestSuitesRoute
  '/results/$analysisId': typeof AuthenticatedResultsAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/api-tester': typeof AuthenticatedApiTesterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/locator-sandbox': typeof AuthenticatedLocatorSandboxRoute
  '/_authenticated/new-analysis': typeof AuthenticatedNewAnalysisRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/qa-guide': typeof AuthenticatedQaGuideRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/test-suites': typeof AuthenticatedTestSuitesRoute
  '/_authenticated/results/$analysisId': typeof AuthenticatedResultsAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api-tester'
    | '/dashboard'
    | '/history'
    | '/locator-sandbox'
    | '/new-analysis'
    | '/prompts'
    | '/qa-guide'
    | '/settings'
    | '/test-suites'
    | '/results/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/api-tester'
    | '/dashboard'
    | '/history'
    | '/locator-sandbox'
    | '/new-analysis'
    | '/prompts'
    | '/qa-guide'
    | '/settings'
    | '/test-suites'
    | '/results/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/api-tester'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/locator-sandbox'
    | '/_authenticated/new-analysis'
    | '/_authenticated/prompts'
    | '/_authenticated/qa-guide'
    | '/_authenticated/settings'
    | '/_authenticated/test-suites'
    | '/_authenticated/results/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test-suites': {
      id: '/_authenticated/test-suites'
      path: '/test-suites'
      fullPath: '/test-suites'
      preLoaderRoute: typeof AuthenticatedTestSuitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa-guide': {
      id: '/_authenticated/qa-guide'
      path: '/qa-guide'
      fullPath: '/qa-guide'
      preLoaderRoute: typeof AuthenticatedQaGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-analysis': {
      id: '/_authenticated/new-analysis'
      path: '/new-analysis'
      fullPath: '/new-analysis'
      preLoaderRoute: typeof AuthenticatedNewAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locator-sandbox': {
      id: '/_authenticated/locator-sandbox'
      path: '/locator-sandbox'
      fullPath: '/locator-sandbox'
      preLoaderRoute: typeof AuthenticatedLocatorSandboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-tester': {
      id: '/_authenticated/api-tester'
      path: '/api-tester'
      fullPath: '/api-tester'
      preLoaderRoute: typeof AuthenticatedApiTesterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$analysisId': {
      id: '/_authenticated/results/$analysisId'
      path: '/results/$analysisId'
      fullPath: '/results/$analysisId'
      preLoaderRoute: typeof AuthenticatedResultsAnalysisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiTesterRoute: typeof AuthenticatedApiTesterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLocatorSandboxRoute: typeof AuthenticatedLocatorSandboxRoute
  AuthenticatedNewAnalysisRoute: typeof AuthenticatedNewAnalysisRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedQaGuideRoute: typeof AuthenticatedQaGuideRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTestSuitesRoute: typeof AuthenticatedTestSuitesRoute
  AuthenticatedResultsAnalysisIdRoute: typeof AuthenticatedResultsAnalysisIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiTesterRoute: AuthenticatedApiTesterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLocatorSandboxRoute: AuthenticatedLocatorSandboxRoute,
  AuthenticatedNewAnalysisRoute: AuthenticatedNewAnalysisRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedQaGuideRoute: AuthenticatedQaGuideRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTestSuitesRoute: AuthenticatedTestSuitesRoute,
  AuthenticatedResultsAnalysisIdRoute: AuthenticatedResultsAnalysisIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
